/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SSMSystem;

import DataBaseWork.MySqlConnection;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Microsoft
 */
public class AddEmployee extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     */
    public AddEmployee() {
        initComponents();
        fillComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EmpNameTF = new javax.swing.JTextField();
        EmpEmailTF = new javax.swing.JTextField();
        EmpNoTF = new javax.swing.JTextField();
        EmpPwd = new javax.swing.JTextField();
        EmpSalaryTF = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        ClearButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(550, 80, 0, 0));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 128, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 191, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Employee Phone No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 254, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Employee Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 317, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Employee Join date(dd/mm/yy)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Employee Salary");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 443, -1, -1));

        EmpNameTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmpNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpNameTFActionPerformed(evt);
            }
        });
        getContentPane().add(EmpNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 125, 310, -1));

        EmpEmailTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmpEmailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpEmailTFActionPerformed(evt);
            }
        });
        getContentPane().add(EmpEmailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 188, 310, -1));

        EmpNoTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(EmpNoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 251, 310, -1));

        EmpPwd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(EmpPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 314, 310, -1));

        EmpSalaryTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(EmpSalaryTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 440, 310, -1));

        AddButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, 100, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 310, -1));

        ClearButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 100, -1));

        RemoveButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RemoveButton.setText("Remove");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RemoveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/exit (1).png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Select Employee To Remove");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jDateChooser1.setDateFormatString("yyyy-MM-dd\n");
        jDateChooser1.setMinimumSize(new java.awt.Dimension(6, 28));
        jDateChooser1.setPreferredSize(new java.awt.Dimension(6, 28));
        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser1MouseClicked(evt);
            }
        });
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 310, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add-Employee-SSMS.gif"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        String empName = EmpNameTF.getText();
        String empEmail = EmpEmailTF.getText();
        String empphoneNo = EmpNoTF.getText();
        String empPwd = EmpPwd.getText();
        String empJoinDate = ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText();
        int empSalary = Integer.parseInt(EmpSalaryTF.getText());
        
        if (EmpNameTF.getText().equals("") || EmpEmailTF.getText().equals("") || EmpNoTF.getText().equals("") || EmpPwd.getText().equals("") || EmpSalaryTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Provide Complete Information", "", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Connection con = MySqlConnection.getCon();
                
                String query = "ALTER TABLE addemployee AUTO_INCREMENT=1;";
                PreparedStatement ps = con.prepareStatement(query);
                ps.execute();
                
                if (empphoneNo.length() == 11 && empPwd.length() >= 8) {
                    query = "INSERT INTO addemployee VALUES(?,?,?,?,?,?,?)";
                    ps = con.prepareStatement(query);
                    ps.setString(1, null);
                    ps.setString(2, empName);
                    ps.setString(3, empEmail);
                    ps.setString(4, empphoneNo);
                    ps.setString(5, empPwd);
                    ps.setString(6, empJoinDate);
                    ps.setInt(7, empSalary);
                    ps.executeUpdate();
                    
                    new AddEmployee().setVisible(true);
                    JOptionPane.showMessageDialog(null, "Employee Added Successfully!");
                } else {
                    JOptionPane.showMessageDialog(null, "Phone No. & Password length should be 11 and 8 respectively!", "", JOptionPane.ERROR_MESSAGE);
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e, "Error:", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_AddButtonActionPerformed
    
    public void fillComboBox2() {
        String getSelectedName = jComboBox1.getSelectedItem().toString();
        try {
            Connection con = MySqlConnection.getCon();
            String query = "select * from addemployee WHERE emp_name='" + getSelectedName + "'";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                jComboBox1.addItem(rs.getString("emp_name"));
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void fillComboBox() {
        try {
            Connection con = MySqlConnection.getCon();
            String query = "select * from addemployee;";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                jComboBox1.addItem(rs.getString("emp_name"));
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void EmpNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpNameTFActionPerformed

    private void EmpEmailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpEmailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpEmailTFActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        AdminOptionsScreen aos = new AdminOptionsScreen();
        aos.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        EmpNameTF.setText("");
        EmpEmailTF.setText("");
        EmpNoTF.setText("");
        EmpPwd.setText("");
//        EmpDateTF.setText("");
        EmpSalaryTF.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String emp_name = jComboBox1.getSelectedItem().toString();
        String emp_phoneNo = "";
        String password = "";
        String joinDate = "";
        int Salary = 0;
        String emp_email = "";
        
        try {
            Connection con = MySqlConnection.getCon();
            String query = "Select * from addemployee WHERE emp_name='" + emp_name + "'";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery(query);
            while (rs.next()) {
                emp_email = rs.getString(3);
                emp_phoneNo = rs.getString(4);
                password = rs.getString(5);
                joinDate = rs.getString(6);
                Salary = rs.getInt(7);
            }
            
            System.out.println(joinDate);
            EmpNameTF.setText(jComboBox1.getSelectedItem().toString());
            EmpEmailTF.setText(emp_email);
            EmpNoTF.setText(emp_phoneNo);
            EmpPwd.setText(password);
//            jDateChooser1.setDate(joinDate);
            java.util.Date date2 = new SimpleDateFormat("yyyy-MM-dd").parse(joinDate);
            jDateChooser1.setDate(date2);
            EmpSalaryTF.setText(String.valueOf(Salary));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        // TODO add your handling code here:
        String removeEmployee = jComboBox1.getSelectedItem().toString();
        if (jComboBox1.getSelectedItem().equals("Select")) {
            JOptionPane.showMessageDialog(null, "Please select the employee to remove", "", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Connection con = MySqlConnection.getCon();
                String query = "DELETE FROM addemployee WHERE emp_name='" + removeEmployee + "'";
                PreparedStatement ps = con.prepareStatement(query);
                ps.execute();
                
                query = "update addemployee ae\n"
                        + "JOIN\n"
                        + "(\n"
                        + "SELECT ROW_NUMBER() OVER (\n"
                        + "        ORDER BY emp_id\n"
                        + "    ) row_num, emp_id\n"
                        + "    FROM addemployee\n"
                        + ")AS rw_num \n"
                        + "ON ae.emp_id = rw_num.emp_id\n"
                        + "set ae.emp_id = rw_num.row_num";
                ps = con.prepareStatement(query);
                ps.execute();
                
                JOptionPane.showMessageDialog(null, "Employee has been removed successfully!");
                EmpNameTF.setText("");
                EmpEmailTF.setText("");
                EmpNoTF.setText("");
                EmpPwd.setText("");
                EmpSalaryTF.setText("");
                jDateChooser1.setDate(null);
                new AddEmployee().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void jDateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jDateChooser1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JTextField EmpEmailTF;
    private javax.swing.JTextField EmpNameTF;
    private javax.swing.JTextField EmpNoTF;
    private javax.swing.JTextField EmpPwd;
    private javax.swing.JTextField EmpSalaryTF;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
