/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SSMSystem;

import DataBaseWork.MySqlConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Microsoft
 */
public class AddSupplier extends javax.swing.JFrame {

    /**
     * Creates new form AddSupplier
     */
    public AddSupplier() {
        initComponents();
        fillComboBox();
        SupplierTextField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SupplierTextField = new javax.swing.JTextField();
        AddSupplier = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        RemoveSupplier = new javax.swing.JButton();
        SupplierComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(540, 200, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/exit (1).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Supplier Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 168, -1, -1));

        SupplierTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SupplierTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(SupplierTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 165, 333, -1));

        AddSupplier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddSupplier.setText("Add");
        AddSupplier.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddSupplier.setMaximumSize(new java.awt.Dimension(95, 31));
        AddSupplier.setMinimumSize(new java.awt.Dimension(95, 31));
        AddSupplier.setPreferredSize(new java.awt.Dimension(95, 31));
        AddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(AddSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        ClearButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ClearButton.setMaximumSize(new java.awt.Dimension(95, 31));
        ClearButton.setMinimumSize(new java.awt.Dimension(95, 31));
        ClearButton.setPreferredSize(new java.awt.Dimension(95, 31));
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        RemoveSupplier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RemoveSupplier.setText("Remove");
        RemoveSupplier.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RemoveSupplier.setMaximumSize(new java.awt.Dimension(95, 31));
        RemoveSupplier.setMinimumSize(new java.awt.Dimension(95, 31));
        RemoveSupplier.setPreferredSize(new java.awt.Dimension(95, 31));
        RemoveSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(RemoveSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        SupplierComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SupplierComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(SupplierComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 87, 333, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select Supplier To Remove");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Supplier-SSMS.gif"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        AdminOptionsScreen aos = new AdminOptionsScreen();
        aos.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void SupplierTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierTextFieldActionPerformed

    private void AddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSupplierActionPerformed
        // TODO add your handling code here:
        String SupplierName = SupplierTextField.getText();
        if (SupplierTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Supplier Name is not entered!", "", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Connection con = MySqlConnection.getCon();
                String query = "ALTER TABLE supplier AUTO_INCREMENT=1;";
                PreparedStatement ps = con.prepareStatement(query);
                ps.execute();
                
                query = "insert into supplier values (?,?)";
                ps = con.prepareStatement(query);
                ps.setString(1, null);
                ps.setString(2, SupplierName);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Supplier Added Successfully");
                fillComboBox2();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_AddSupplierActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        SupplierTextField.setText("");
        SupplierComboBox.setSelectedItem("Select");
        new AddSupplier().setVisible(true);
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void RemoveSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveSupplierActionPerformed
        // TODO add your handling code here:
        String selectedSupplier = SupplierComboBox.getSelectedItem().toString();
//        SupplierTextField.setText(selectedSupplier);
        if (SupplierComboBox.getSelectedItem().toString().equals("Select")) {
            JOptionPane.showMessageDialog(null, "Select Supplier to Remove!", "", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Connection con = MySqlConnection.getCon();
                String query = "DELETE from supplier WHERE supplier_name='" + selectedSupplier + "';";
                PreparedStatement ps = con.prepareStatement(query);
                ps.execute();
                
                query = "update supplier supp\n"
                        + "JOIN\n"
                        + "(\n"
                        + "SELECT ROW_NUMBER() OVER (\n"
                        + "        ORDER BY supplier_id\n"
                        + "    ) row_num, supplier_id\n"
                        + "    FROM supplier\n"
                        + ")AS rw_num \n"
                        + "ON supp.supplier_id = rw_num.supplier_id\n"
                        + "set supp.supplier_id = rw_num.row_num";
                ps = con.prepareStatement(query);
                ps.execute();
                SupplierTextField.setText("");
                JOptionPane.showMessageDialog(null, "Supplier Removed Successfully", "", JOptionPane.ERROR_MESSAGE);
//                SupplierComboBox.setSelectedItem(null);
                AddSupplier as = new AddSupplier();
                as.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_RemoveSupplierActionPerformed

    private void SupplierComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierComboBoxActionPerformed
        // TODO add your handling code here:
        SupplierTextField.setText(SupplierComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_SupplierComboBoxActionPerformed
    public void fillComboBox() {
        try {
            Connection con = MySqlConnection.getCon();
            String query = "select * from supplier;";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                SupplierComboBox.addItem(rs.getString("supplier_name"));
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void fillComboBox2() {
        try {
            String SupplierName = SupplierTextField.getText();
            Connection con = MySqlConnection.getCon();
            String query = "select * from supplier WHERE supplier_name='" + SupplierName + "';";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                SupplierComboBox.addItem(rs.getString("supplier_name"));
            }
            con.close();
            SupplierTextField.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSupplier;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton RemoveSupplier;
    private javax.swing.JComboBox<String> SupplierComboBox;
    private javax.swing.JTextField SupplierTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
